version: '3.8'
networks:
  administrasi:
services:
  nginx_administrasi:
    image: nginx:alpine
    container_name: nginx_administrasi
    ports:
      - '8070:8070'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - administrasi
      - administrasi_db
    networks:
      - administrasi

  administrasi_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'dimas'
      POSTGRES_PASSWORD: 'dimasw1950'
      POSTGRES_DB: 'administrasi'
    ports:
      - '5445:5432'
    networks:
      - administrasi

  administrasi:
    container_name: administrasi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - administrasi

  cloudflared_administrasi:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_administrasi
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZGRlZTM4YmMyNDBlYTIzZjQ1OTlmNjI4MmEyNGMyMTUiLCJ0IjoiNmM0ZDY4NTItZjk5NC00ZTViLWFhZTUtZDQ5M2E0ZjM2NjgyIiwicyI6IlpETXlNR1prTVRBdFpqWXlOeTAwWlRobExXRmpNRE10TkRBMVpHTmtPV1F5TVRKbSJ9
    depends_on:
      - nginx_administrasi
    networks:
      - administrasi